db_bench: ErrorExit from static func compiler error (#277)
while we're at it, also, remove the need to add an exit(1) after ErrorExit
to stop compiler complaining about :
error: control reaches end of non-void function